### ISSUE TITLE
Get error when build hermes2_installer.jar

### ISSUE THREAD

**Issue by Alan-Chen-au** [cecid/hermes#5]
**want to build hermes2_installer.jar from source code (on Mac). Get error when run : mvn install. Detail information listed below.** 

Tests in error: 
hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest.testDecryption(hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest)
  Run 1: IncomingMessageProcessorTest>SystemComponentTest.before:48 » Module Unable to ...
  Run 2: IncomingMessageProcessorTest>SystemComponentTest.after:64->tearDown:172 NullPointer

hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest.testDecryptionSignatureVerfication(hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest)
  Run 1: IncomingMessageProcessorTest>SystemComponentTest.before:48 » Module Unable to ...
  Run 2: IncomingMessageProcessorTest>SystemComponentTest.after:64->tearDown:172 NullPointer

hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest.testSignatureVerfication(hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest)
  Run 1: IncomingMessageProcessorTest>SystemComponentTest.before:48 » Module Unable to ...
  Run 2: IncomingMessageProcessorTest>SystemComponentTest.after:64->tearDown:172 NullPointer

hk.hku.cecid.edi.as2.module.test.OutgoingMessageProcessorTest.testCompressAS2Message(hk.hku.cecid.edi.as2.module.test.OutgoingMessageProcessorTest)
  Run 1: OutgoingMessageProcessorTest>SystemComponentTest.before:48 » Module Unable to ...
  Run 2: OutgoingMessageProcessorTest>SystemComponentTest.after:64->tearDown:128->SystemComponentTest.commitSQL:90 » NullPointer

hk.hku.cecid.edi.as2.module.test.OutgoingMessageProcessorTest.testEncrytedAS2Message(hk.hku.cecid.edi.as2.module.test.OutgoingMessageProcessorTest)
  Run 1: OutgoingMessageProcessorTest>SystemComponentTest.before:48 » Module Unable to ...
  Run 2: OutgoingMessageProcessorTest>SystemComponentTest.after:64->tearDown:128->SystemComponentTest.commitSQL:90 » NullPointer

hk.hku.cecid.edi.as2.module.test.OutgoingMessageProcessorTest.testPlainMessageMIC(hk.hku.cecid.edi.as2.module.test.OutgoingMessageProcessorTest)
  Run 1: OutgoingMessageProcessorTest>SystemComponentTest.before:48 » Module Unable to ...
  Run 2: OutgoingMessageProcessorTest>SystemComponentTest.after:64->tearDown:128->SystemComponentTest.commitSQL:90 » NullPointer

hk.hku.cecid.edi.as2.module.test.OutgoingMessageProcessorTest.testSignedAS2Message(hk.hku.cecid.edi.as2.module.test.OutgoingMessageProcessorTest)
  Run 1: OutgoingMessageProcessorTest>SystemComponentTest.before:48 » Module Unable to ...
  Run 2: OutgoingMessageProcessorTest>SystemComponentTest.after:64->tearDown:128->SystemComponentTest.commitSQL:90 » NullPointer

hk.hku.cecid.edi.as2.module.test.OutgoingMessageProcessorTest.testSignedCommpressMessage(hk.hku.cecid.edi.as2.module.test.OutgoingMessageProcessorTest)
  Run 1: OutgoingMessageProcessorTest>SystemComponentTest.before:48 » Module Unable to ...
  Run 2: OutgoingMessageProcessorTest>SystemComponentTest.after:64->tearDown:128->SystemComponentTest.commitSQL:90 » NullPointer

hk.hku.cecid.edi.as2.module.test.OutgoingMessageProcessorTest.testSignedEncryptedAS2Message(hk.hku.cecid.edi.as2.module.test.OutgoingMessageProcessorTest)
  Run 1: OutgoingMessageProcessorTest>SystemComponentTest.before:48 » Module Unable to ...
  Run 2: OutgoingMessageProcessorTest>SystemComponentTest.after:64->tearDown:128->SystemComponentTest.commitSQL:90 » NullPointer

Tests run: 13, Failures: 0, Errors: 9, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Hermes 2 Message Gateway ........................... SUCCESS [  2.013 s]
[INFO] Piazza Commons ..................................... SUCCESS [  2.767 s]
[INFO] Corvus Webapp ...................................... SUCCESS [  0.794 s]
[INFO] Corvus Main ........................................ SUCCESS [  0.656 s]
[INFO] Corvus Admin ....................................... SUCCESS [  0.167 s]
[INFO] EbMS Package ....................................... SUCCESS [  0.073 s]
[INFO] Corvus EbMS ........................................ SUCCESS [  2.066 s]
[INFO] Corvus EbMS Admin .................................. SUCCESS [  0.920 s]
[INFO] Corvus AS2 ......................................... SUCCESS [  0.149 s]
[INFO] Corvus AS2 Admin ................................... SUCCESS [  0.837 s]
[INFO] Corvus AS2Plus ..................................... FAILURE [  9.311 s]
[INFO] Corvus AS2Plus Admin ............................... SKIPPED
[INFO] Corvus Main Admin .................................. SKIPPED
[INFO] Corvus SFRM ........................................ SKIPPED
[INFO] Corvus SFRM Admin .................................. SKIPPED
[INFO] Corvus Web Service Client .......................... SKIPPED
[INFO] Corvus API ......................................... SKIPPED
[INFO] Loopback Test ...................................... SKIPPED
[INFO] H2O Installer ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.946 s
[INFO] Finished at: 2018-09-11T16:00:16+10:00
[INFO] Final Memory: 22M/323M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project corvus-as2plus: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/achen/Documents/workspace/hermes-master/target/junit-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project corvus-as2plus: There are test failures.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~
**more error info from junit-reports directory :** 

-------------------------------------------------------------------------------
Test set: hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest
-------------------------------------------------------------------------------
Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.079 sec <<< FAILURE! - in hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest
testSignatureVerfication(hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest)  Time elapsed: 0.011 sec  <<< ERROR!
hk.hku.cecid.piazza.commons.module.ModuleException: Unable to initialize module group 'AS2 Module Group'
Caused by: hk.hku.cecid.piazza.commons.module.ModuleException: Unable to load modules
Caused by: hk.hku.cecid.piazza.commons.module.ModuleException: Unable to initialize component 'AS2 Key Store Manager'
Caused by: hk.hku.cecid.piazza.commons.security.KeyStoreManagementException: Unable to initialize the key store
Caused by: java.io.IOException: exception unwrapping private key - java.security.InvalidKeyException: Illegal key size

testSignatureVerfication(hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.NullPointerException
	at hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest.tearDown(IncomingMessageProcessorTest.java:172)

testDecryptionSignatureVerfication(hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest)  Time elapsed: 0.041 sec  <<< ERROR!
hk.hku.cecid.piazza.commons.module.ModuleException: Unable to initialize module group 'AS2 Module Group'
Caused by: hk.hku.cecid.piazza.commons.module.ModuleException: Unable to load modules
Caused by: hk.hku.cecid.piazza.commons.module.ModuleException: Unable to initialize component 'AS2 Key Store Manager'
Caused by: hk.hku.cecid.piazza.commons.security.KeyStoreManagementException: Unable to initialize the key store
Caused by: java.io.IOException: exception unwrapping private key - java.security.InvalidKeyException: Illegal key size

testDecryptionSignatureVerfication(hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest)  Time elapsed: 0.041 sec  <<< ERROR!
java.lang.NullPointerException
	at hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest.tearDown(IncomingMessageProcessorTest.java:172)

testDecryption(hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest)  Time elapsed: 0.026 sec  <<< ERROR!
hk.hku.cecid.piazza.commons.module.ModuleException: Unable to initialize module group 'AS2 Module Group'
Caused by: hk.hku.cecid.piazza.commons.module.ModuleException: Unable to load modules
Caused by: hk.hku.cecid.piazza.commons.module.ModuleException: Unable to initialize component 'AS2 Key Store Manager'
Caused by: hk.hku.cecid.piazza.commons.security.KeyStoreManagementException: Unable to initialize the key store
Caused by: java.io.IOException: exception unwrapping private key - java.security.InvalidKeyException: Illegal key size

testDecryption(hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest)  Time elapsed: 0.026 sec  <<< ERROR!
java.lang.NullPointerException
	at hk.hku.cecid.edi.as2.module.test.IncomingMessageProcessorTest.tearDown(IncomingMessageProcessorTest.java:172)

**Comment by tomlee** [comment]
Thanks. Will try to repeat this in my environment when I have time.

**Comment by Alan-Chen-au** [comment]
Thanks Tom. 

Environment info is listed as below : 
1) Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T17:58:13+10:00)
2) Java version: 1.8.0_74
3) OS : "mac os x", version: "10.13.4", arch: "x86_64", family: "mac"

Let me know if you need further info. 

Regards,
Alan
